### ISSUE TITLE
Authconfig for buildImage possible?

### ISSUE THREAD

**Issue by ekristen** [apocas/dockerode#151]
Is it possible to pass an authconfig object to the buildImage function?

**Comment by apocas** [comment]
Yes just use in the same was as docker.pull.

If the authconfig property is in the options object docker-modem will always build the "X-Registry-Auth" header accordingly, so it will work.

https://github.com/apocas/docker-modem/blob/master/lib/modem.js#L116

**Comment by ekristen** [comment]
I saw that line of code, but that is not the behavior I am seeing. If you pass `authconfig` to the main options when declaring an instance of dockerode, `var docker = new dockerode({authconfig: ...})` then yes that line 116 is valid, however if you simply pass `authconfig` to `buildImage` line 116 is not valid because the options object in docker-modem that is passed to buildImage looks like this ...

```
{
  path: '/build',
  ...
  options: {
     ...
     authconfig: "..."
   }
}
```

**Comment by apocas** [comment]
Don't send the authconfig in a inner object, try this:
docker.buildImage('archive.tar', {'t': imageName, 'authconfig': auth, ...}, function (err, response){
  //...
});

**Comment by ekristen** [comment]
I'm using dockerode 2.1.5 and docker-modem 0.2.5 and that is not correct based on what I am seeing. This is the code I'm using ...

```javascript
docker.buildImage(tarStream, {
   t: b.tag,
   authconfig: registry_configs['index.private.io']
}, function(err, stream) {
   ...
})
```

I put a `console.log` on **options** at **Line 115** here is the output 

```
{ path: '/build?',
  method: 'POST',
  file:
   { _readableState:
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: false,
        calledRead: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     _drain: [Function],
     _finalized: false,
     _finalizing: false,
     _destroyed: false,
     _stream: null },
  options:
   { t: 'index.private.io/myimage/testing:v1.0.0',
     authconfig:
      { auth: '',
        email: 'admin@private.io',
        username: 'admin',
        password: 'admin',
        serveraddress: 'index.private.io' } },
  isStream: true,
  statusCodes: { '200': true, '500': 'server error' } }
```

Line 116 wants `authconfig` at the same level as path and method, but in this case it is not.

**Comment by apocas** [comment]
Yup my bad.

I just pushed a quick patch for this into the master branch, give it a try.
https://github.com/apocas/dockerode/commit/66cadee2de3bdc9b06655ec0df0a48f41e94e004

I'm currently on the go right now, so I couldn't test it nor ran the test suite.
Later today I will prep the next version and tackle this.

**Comment by ekristen** [comment]
@apocas appreciate it, I understand being on the go. I just did a quick test, the options look right now, but I'm still having a 403 error, but I think that might be on my side, I'll have to do some more debugging to be sure.

**Comment by apocas** [comment]
authconfig support in build published in v2.2.0
