### ISSUE TITLE
Cannot pull image on windows

### ISSUE THREAD

**Issue by vxsx** [apocas/dockerode#347]
This snippet:

```
return new Promise((resolve, reject) => {
        docker.pull('any image', (error, stream) => {
            docker.modem.followProgress(stream, (error, output) => {
                if (error) {
                    reject(error);
                    return;
                }
                resolve(output);
            }, (event) => console.log(event));
        });
})
```
always rejects on windows with "context canceled" as error message. The Docker logs show something like this:

```
[16:57:26.956][ApiProxy       ][Info   ] proxy >> POST /v1.26/images/create?fromImage=postgres&tag=latest
[16:57:26.957][ApiProxy       ][Info   ] Dial Hyper-V socket 6f1ec07b-ba85-4cb4-ad22-d0e2577b8f24:23a432c2-537a-4291-bcb5-d62504644739
[16:57:26.958][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 6f1ec07b-ba85-4cb4-ad22-d0e2577b8f24:23a432c2-537a-4291-bcb5-d62504644739
[16:58:08.637][ApiProxy       ][Info   ] Cancel connection...
[16:58:08.641][ApiProxy       ][Info   ] proxy << POST /v1.26/images/create?fromImage=postgres&tag=latest
```

Normal `docker pull imagename` works inside powershell
Latest Docker for Windows.

It might be a problem with Docker for Windows itself, but any help would be really appreciated. Same snippet works correctly on mac and linux

**Comment by snat0x54** [comment]
Same problem here using dockerode 2.4.3 and docker 17.04.0-ce-rc2

**Comment by igor-lemon** [comment]
+1

**Comment by pashist** [comment]
Same issue 
Docker version 17.03.1-ce 
dockerode 2.4.3

**Comment by nlaplante** [comment]
Same issue. Same config as @pashist

**Comment by nlaplante** [comment]
I'm still baffled with this. I'm not sure if it's an issue from dockerode or docker-modem or Docker itself. If I try again and again, sometimes images will pull successfully. But most of the time (9 times out of 10) it fails with *context canceled*.

I also tried without using *modem.followProgress* and the error still happens.

**Comment by Eikc** [comment]
This also happens in "node-docker-api" npm package that uses docker-modem, so i think this issue is a docker-modem issue.

**Comment by xblackhand** [comment]
I was playing around with the [https://github.com/apocas/docker-modem/blob/master/lib/modem.js] to see why the pull function from dockerode was giving me a 'Error: context canceled' message.   I got the pull to work with various images by commenting out **req.end()** on **line 238**.   

Not sure what repercussions this will have, but hope it gives the contributors an idea where to start to fix this correctly.

**Comment by nlaplante** [comment]
Tried commenting out **req.send()** as suggested by @xblackhand but it broke other functionality like listing images & containers (timeout). BTW on docker-modem v1.0.0, the line # is 234 and not 238.

**Comment by nlaplante** [comment]
Maybe this is related to [this docker-modem issue](https://github.com/apocas/docker-modem/issues/83) _(Requests that return HttpDuplex (eg docker exec start) hang when using named pipe on windows.)?_

**Comment by brucedjones** [comment]
Any update on this?

**Comment by masaeedu** [comment]
Not 100% sure, but I think the issue might be that you actually have to wait for the response output from HTTP request to finish before you can consider the image to have been fully pulled. I have a Docker client library that I autogenerate from the Docker swagger API [here](https://www.npmjs.com/package/docker-client) and ran into the same issue: I was assuming the moment I got a response from the server I was good to go, whereas in fact I need to consume the output stream and only once that is done can I consider the image pulled.

**Comment by sochix** [comment]
+1

**Comment by langk** [comment]
+1

**Comment by rssk** [comment]
This was plaguing our Windows builds so I dug a bit deeper, the results can be found [here](https://github.com/apocas/docker-modem/issues/90) as it's an issue w/ docker-modem. Super interesting the Docker daemon seems to respond differently on win vs osx, but I assume that's due to HyperV differences?

Either way, if you're hurting for a solution you can just do pulls with plain ol' node `http`:


```js
const http = require('http');

const options = {
  socketPath: '//./pipe/docker_engine',
  path: '/v1.37/images/create?fromImage=coinstac%2Fcoinstac-base',
  method: 'POST',
};

const callback = res => {
  console.log(`STATUS: ${res.statusCode}`);
  res.setEncoding('utf8');
  res.on('data', data => console.log(data));
  res.on('error', data => console.error(data));
};

const clientRequest = http.request(options, callback);
clientRequest.end();
```

Hope that helps!

**Comment by KingRial** [comment]
Here the great workaround described by @rssk using **basic authentication** and **private registry**:

```javascript
var clientRequest = http.request({
  socketPath: '//./pipe/docker_engine',
  path: '/images/create?fromImage=' + REGISTRY_HOST + '%2F' + IMAGE_NAME + '&tag=' + IMAGE_TAG,
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'X-Registry-Auth': new Buffer(JSON.stringify({ username: REGISTRY_USERNAME, password: REGISTRY_PASSOWRD, serveraddress: REGISTRY_HOST})).toString('base64')
  }
}, (res) => {
  res.setEncoding('utf8');
  res.on('data', data => console.log(data));
  res.on('error', data => console.error(data));
});
clientRequest.end();
```

**Comment by apocas** [comment]
Is this still an issue?

I'm able to run the image pull test on Windows.
https://github.com/apocas/dockerode/blob/master/test/docker.js#L184

Using Windows 10 and latest Docker version.

**Comment by pofallon** [comment]
I believe it may have been resolved.  I was also experiencing this error previously, but with everything at the latest version it now works.

**Comment by bj00rn** [comment]
@apocas still an issue for me. 
"dockerode": "2.5.7", 
Docker Version 18.06.1-ce-win73 (19507)
Win 10

**Comment by bj00rn** [comment]
Can confirm this issue with Docker Version 2.0.0.0-win81 (29211) (Engine 18.09.0) too

**Comment by apocas** [comment]
Closing this one, reopen if needed.
